[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib", "../node_modules"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 10_000
via_ir = true
remappings = [
  "@openzeppelin/contracts/=../node_modules/@openzeppelin/contracts/",
  "forge-std/=lib/forge-std/src/"
]

[fuzz]
runs = 1_000

[invariant]
runs = 256
depth = 64
fail_on_revert = false
